name: KBA Daten aktualisieren

on:
  schedule:
    - cron: '0 8 7 * *'
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: |
          pip install requests PyMuPDF gspread oauth2client

      - name: credentials.json bereitstellen
        run: echo "${{ secrets.GSHEET_CREDENTIALS }}" > credentials.json

      - name: Skript ausführen
        run: python main.py
