name: Update Google Sheet

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Write Google credentials to credentials.json
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > credentials.json
      - name: Run Python script
        run: python main.py
